### ISSUE TITLE
first :o

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/RTG-1.8.9#1]
@Team-RTG/readers 

FYI: This 1.8.9 merge is currently broken. There are a bunch of missing commits in the 1.8.9 branch. (such as stuff like https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/54e67a1ce24f0c8417db050ed12589673bb9bcc1).

This is likely because it was forked from master from a much earlier time, then merged with **DEV**, so it's missing commits from inbetween.

I think the best course of action would be to merge **MASTER** into **1.8.9**, then merge **DEV** into **1.8.9** (This might not need to be done, because I think it would be redundant?), then either merge **1.8.9** back into **MASTER**, or make the **1.8.9** branch the default branch. After that, I'd delete all other branches and clone the new default to a new **DEV** for developement purposes.

**Comment by whichonespink44** [comment]
Yeah, I think topi's fork was taken from 0.6.1, so we'll need to get everything from 0.6.2 into the new repo.

However... I'm in uncharted GitHub territory here, so I'm not sure what the best course of action should be, so I'm just gonna start talking off the top of my head here...

I think it was the right to call to import topi's fork into the new repo as a starting point, but yeah, now it's just a case of figuring out how we keep the 1.8 repo in sync with the 1.7 repo... @topisani maybe you already have a strategy for that?

And just to be clear, when I say 'in sync' I'm not including all of the feature branches from the 1.7 repo. They got carried across into the 1.8 repo, but I definitely think we should just delete those in the 1.8 repo, which can have its own feature branches if that's how topi wants to play it.

I kinda think topi should **only** be porting from the 1.7 repo's `master` at any given time... so like... the current 1.7 `master` is 0.6.2, so we should get the 1.8 repo up-to-date with that, but not the stuff from the 1.7 `dev` branch, because that's susceptible to massive change at any given time.

So maybe the workflow should look something like this:

1. Get the 1.8 repo's `master` up-to-date with the 1.7 repo's `master` (currently @ v0.6.2)
2. Release v0.7.0 for 1.7.10
3. Get the 1.8 repo's `master` up-to-date with the 1.7 repo's `master` (v0.7.0)
4. Release v0.8.0 for 1.7.10
5. Get the 1.8 repo's `master` up-to-date with the 1.7 repo's `master` (v0.8.0)

etc.

What does everybody reckon to that?

I'm easy like Sunday morning, so happy to discuss other options. The only thing I'm fairly certain about is that we should only be porting stuff into the 1.8 repo from 1.7.10's `master` at any given time.

**Comment by topisani** [comment]
i think that sounds great, and then, depending on my time when the issues that are specific to 1.8 are resolved, i might be porting some features from your featurebranches. Also all the compatibility issues will probably be quite a bit different between the two versions.

**Comment by topisani** [comment]
I did a bit of merging around this morning, and it now works for me(the master branch).
We're you completely unable to start it, or was there just missing features?

**Comment by topisani** [comment]
i guess its fixed, as that commit you mentioned is now there along with 1300 others
@whichonespink44 i think the main thing will be to keep master up to date with your master, and then i will maybe merge some specific features and such. I will need to see how long it takes when all the 1.8 specific issues are resolved.

**Comment by whichonespink44** [comment]
_"i think the main thing will be to keep master up to date with your master"_

Typical of me to take a few paragraphs and a bullet-point list to explain what could've been said in a single sentence :P

Yeah, that sounds good mate, as long as both masters are in sync as much as possible, it's all good.

**Comment by topisani** [comment]
sync the masters - let one master agree with the other. Its all about the masters

**Comment by srs-bsns** [comment]
This is still not fixed. These should be identical:

https://github.com/Team-RTG/RTG-1.8.9/tree/master/src/main/java/rtg/world/biome/realistic
https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/master/src/main/java/rtg/world/biome/realistic

Maybe it would be prudent to delete this repo and then start from scratch, because it might not be fixable.

**Comment by topisani** [comment]
nope thats because i removed all mod support and unused biomes, cause i couldnt be bothered to port them all now
i will merge them back eventually

**Comment by srs-bsns** [comment]
https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/54e67a1ce24f0c8417db050ed12589673bb9bcc1

This commit is critical to preventing crashes with any mod that RTG doesn't support and it's a part of `master` in 0.6.2, so it should be in the 1.8.9 branch.

**Comment by topisani** [comment]
ok so i guess i should merge 1.7 master... hey thats what you said in the beginning...

**Comment by topisani** [comment]
nope didnt help, i think i might just start all over... kinda

**Comment by topisani** [comment]
@Team-RTG/readers
if anyone knows how to fix this please inform me - cause i have officially given up. Im going to continue fixing trees for now

**Comment by whichonespink44** [comment]
Ok, how about this... (sorry for the bullet-point list - it's an OCD thing!)

1. I'll delete the 1.8 repo.
2. I'll create a new 1.8 repo, except this time I'll import from the current 1.7 `master`.
3. I'll delete all of the feature branches from the new 1.8 repo.
4. @topisani will then merge [his fork](https://github.com/topisani/Realistic-Terrain-Generation) into the new 1.8 repo's `master`.

What does everyone think to that?

**Comment by whichonespink44** [comment]
PLEASE NOTE: I've removed all access to this repo... I'm going to create a new 1.8 repo, but I don't want to get rid of this one just yet in case we need to grab some code/issues from it, etc.

**Comment by Zeno410** [comment]
The problem with keeping them synced is that a lot of calls to doSomething(int x, int y, int z) have been replaced with doSomething(BlockPos pos). There's stuff like that all over biome detail routines, especially decorators. All those calls would need to be written to doSomethingRTG(BlockPos pos) with the 1.7.10 version providing its own BlockPos. 

There are other ways, but they would involve at least similar work.

**Comment by whichonespink44** [comment]
@Zeno410 Maybe that's something I could do when I start implementing the terrain & surface wrappers that we discussed the other day? There will probably be other conflicts that arise even if we write our own BlockPos, but wherever there's an opportunity to do something like that, we might as well if it makes things easier to sync, as long as it doesn't affect performance too much on the 1.7.10 version.

**Comment by topisani** [comment]
replacing coords with blockpos takes me about 40 secs with a bit of find/replace magic
That is basically what i have been doing the entire time, in much larger quantities than a single version update would do

**Comment by topisani** [comment]
a custom BlockPos on 1.7 would make my life a whole lot easier
it would only need the getX, getY and getZ methods i think

**Comment by Zeno410** [comment]
It would be a good idea. The only thing to watch out for is that new BlockPos() creates an object and that will slow down ops in tight loops. The standard solution is to have a mutable BlockPos although IIRC BlockPos in 1.8 is immutable. This actually helps prevent a lot of hard-to-catch bugs but *forcing* immutability creates some problems.

**Comment by Zeno410** [comment]
Hmm, looking at the code I see they already solved it, kinda, with BlockPos.MutableBlockPos. So just use that in tight loops.

**Comment by Zeno410** [comment]
topisani, what other changes did you have to make?

**Comment by topisani** [comment]
ChunkPrimer instead of the blocks[] and metadata[] in chunk generation

**Comment by topisani** [comment]
and some BlockState instead of Block and Metadata. But that one is harder to fake in 1.7 as theres both IBlockState and BlockState and its kinda unclear were wich one goes. Also the world.setblock method takes block, not BlockState. Really its only BlockPos that would be practical

**Comment by topisani** [comment]
This would be the correct use of MutableBlockPos, right?
`//Flowing water.
        if (rand.nextInt(100) == 0) {
			BlockPos.MutableBlockPos bp = new BlockPos.MutableBlockPos(0, 0,0);
    		for(int l18 = 0; l18 < 50; l18++)
    		{
    			int l21 = worldX + rand.nextInt(16) + 8;
    			int k23 = rand.nextInt(rand.nextInt(worldHeight - 16) + 10);
    			int l24 = worldZ + rand.nextInt(16) + 8;
                
    			(new WorldGenLiquids(Blocks.flowing_water)).generate(worldObj, rand, bp.set(l21, k23, l24));
    	`

**Comment by Zeno410** [comment]
If we want to do a semi-automatic merge I think we have to figure a way to do all these things with shared routines. We can't manually merge 150 SurfaceBiomeX files. Seems you could fix any of this with static methods. The code might end up mildly awkward on one side or another but I don't see any options. The Surface routines are probably going to get a fair amount of rework still.

**Comment by topisani** [comment]
if i set up a few find/replace scripts they dont take me very long

**Comment by topisani** [comment]
i ported the entire mod in 7 hours yesterday
